### PR TITLE
Update dependencies and fix checkstyle violations

### PR DESCRIPTION
**Pull request by floscher**
* bump dependency versions to latest versions (https://github.com/JOSM/geojson/commit/dd2a0bdc9f42153500a2e1bfa0307e255b2134bb)
* align the checkstyle-rules better with the ones Jenkins checks against (https://github.com/JOSM/geojson/commit/26e61b6c41501f06118916c4d510422b18445823) and fix some of the checkstyle violations (https://github.com/JOSM/geojson/commit/a116cfb7842657074d7651dbd233c5056bb7e0c3)
* uncomment the Travis CI badge in the `README.md` (https://github.com/JOSM/geojson/commit/79dc8f87fa0b06a6ed1cef40cc155deace3c12a4)

### CODE REVIEW

**Comment by don-vip** [comment]
thanks! :)

**Comment by floscher** [comment]
One thing i just noticed, I just copied the header comment from the checkstyle configuration that is used in Jenkins. It says the license was GPL, but in fact it is Apache for this repository :open_mouth:.

**Comment by don-vip** [comment]
Good catch. Didn't notice as 99% of JOSM plugins use the same licence as JOSM. Well, you know what you have to do now :)

**Comment by floscher** [comment]
I'm already at it and will push it in the next few minutes.

**Pull request merged**
